# Generated by Django 4.2.3 on 2023-07-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
